//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACContentSynchronizer.ClientGui {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ACContentSynchronizer.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        public static string ContentComparing {
            get {
                return ResourceManager.GetString("ContentComparing", resourceCulture);
            }
        }
        
        public static string PackContent {
            get {
                return ResourceManager.GetString("PackContent", resourceCulture);
            }
        }
        
        public static string RefreshingServer {
            get {
                return ResourceManager.GetString("RefreshingServer", resourceCulture);
            }
        }
        
        public static string ServerRefreshed {
            get {
                return ResourceManager.GetString("ServerRefreshed", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        public static string DownloadingManifest {
            get {
                return ResourceManager.GetString("DownloadingManifest", resourceCulture);
            }
        }
        
        public static string ManifestDownloaded {
            get {
                return ResourceManager.GetString("ManifestDownloaded", resourceCulture);
            }
        }
        
        public static string PreparingContent {
            get {
                return ResourceManager.GetString("PreparingContent", resourceCulture);
            }
        }
        
        public static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        public static string TryingToSave {
            get {
                return ResourceManager.GetString("TryingToSave", resourceCulture);
            }
        }
        
        public static string ContentSaved {
            get {
                return ResourceManager.GetString("ContentSaved", resourceCulture);
            }
        }
        
        public static string ApplyingChanges {
            get {
                return ResourceManager.GetString("ApplyingChanges", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string DownloadingContent {
            get {
                return ResourceManager.GetString("DownloadingContent", resourceCulture);
            }
        }
        
        public static string ContentNoNeedToUpdate {
            get {
                return ResourceManager.GetString("ContentNoNeedToUpdate", resourceCulture);
            }
        }
        
        public static string TaskCanceled {
            get {
                return ResourceManager.GetString("TaskCanceled", resourceCulture);
            }
        }
        
        public static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        public static string ContentSize {
            get {
                return ResourceManager.GetString("ContentSize", resourceCulture);
            }
        }
        
        public static string ContentUploaded {
            get {
                return ResourceManager.GetString("ContentUploaded", resourceCulture);
            }
        }
        
        public static string PleaseSelectCar {
            get {
                return ResourceManager.GetString("PleaseSelectCar", resourceCulture);
            }
        }
        
        public static string TrackPreviewNotAllowed {
            get {
                return ResourceManager.GetString("TrackPreviewNotAllowed", resourceCulture);
            }
        }
        
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        public static string ConnectionEstablishedError {
            get {
                return ResourceManager.GetString("ConnectionEstablishedError", resourceCulture);
            }
        }
        
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string ServerPresets {
            get {
                return ResourceManager.GetString("ServerPresets", resourceCulture);
            }
        }
    }
}
